---
- name: postfix is installed
  apt: pkg=postfix state=installed
  tags: postfix

- name: postfix is configured
  template:
    dest: /etc/postfix/main.cf
    src: main.cf.j2
  notify:
    - restart postfix

- name: postfix is running
  service: name=postfix state=started enabled=yes
  tags: postfix
